services:
  - type: web
    name: assidcoff
    env: docker
    buildCommand: docker build -t assidcoff .
    startCommand: docker run -p $PORT:80 assidcoff
    envVars:
      - key: DB_HOST
        sync: false
      - key: DB_NAME
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
